version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npx ng build --configuration production
      - ls -R dist

artifacts:
  base-directory: dist/my-angular-project
  files:
    - '**/*'